name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: clang64, env: clang-x86_64, branch: v7.2.0 }
#           - { sys: clang32, env: clang-i686, branch: v7.2.0 }
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Cache checked out qemu code
        id: cache-checkout
        uses: actions/cache@v3
        with:
          key: qemu-${{ matrix.branch }}-${{ runner.os }}
          path: ${{ github.workspace }}/qemu
      - if: ${{ steps.cache-checkout.outputs.cache-hit != 'true' }}
        name: Check out qemu
        uses: actions/checkout@v3
        with:
          repository: qemu/qemu
          ref: v7.2.0
          submodules: true
          path: qemu
      - name: Set up build environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: |
            diffutils
            git
            make
            ninja
            patch
            mingw-w64-${{matrix.env}}-glib2
            mingw-w64-${{matrix.env}}-libiconv
            mingw-w64-${{matrix.env}}-libslirp
            mingw-w64-${{matrix.env}}-ncurses
            mingw-w64-${{matrix.env}}-pixman
            mingw-w64-${{matrix.env}}-python
            mingw-w64-${{matrix.env}}-toolchain
      - name: Build
        working-directory: ${{github.workspace}}\qemu
        shell: msys2 {0}
        run: |
          pwd
          env
          ls /clang64
          ls /clang64/include
          ls /clang64/include/ncurses
          patch -Np1 < ../win-clang-disable-safe-stack.patch || true
          C_INCLUDE_PATH=/clang64/include/ncurses ./configure \
            --prefix="${MINGW_PREFIX}" \
            --disable-werror \
            --static \
            --enable-strip \
            --enable-lto \
            --target-list=x86_64-softmmu \
            --without-default-features \
            --without-default-devices \
            --enable-curses \
            --enable-iconv \
            --enable-slirp \
            --enable-tcg \
            --enable-whpx \
            --enable-zstd
          ninja -C build install
