name: Build
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
env:
  QEMU_VERSION: '7.2.0'
  SLIRP_VERSION: '4.7.0'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { arch: x86_64, cc: clang, cxx: clang++, ld: lld }
    steps:
      - name: Cache checked out qemu code
        id: cache-checkout
        uses: actions/cache@v3
        with:
          key: qemu-${{ matrix.branch }}-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.arch }}
          path: ${{ github.workspace }}/qemu
      - if: ${{ steps.cache-checkout.outputs.cache-hit != 'true' }}
        name: Check out qemu
        uses: actions/checkout@v3
        with:
          repository: qemu/qemu
          ref: v${{ env.QEMU_VERSION }}
          submodules: true
          path: qemu
      - name: Set up build environment
        run: |
          sudo apt-get install -y \
            build-essential \
            clang \
            git \
            lld \
            libglib2.0-dev \
            libpixman-1-dev \
            libzstd-dev \
            meson \
            pkg-config \
            python3 \
            ninja-build \
      - name: Build slirp
        working-directory: ${{ github.workspace }}
        run: |
          git clone https://gitlab.freedesktop.org/slirp/libslirp.git -b v$SLIRP_VERSION
          cd libslirp
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} meson setup -Ddefault_library=static build
          sudo ninja -C build install
      - name: Build qemu
        working-directory: ${{ github.workspace }}/qemu
        run: |
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} LD=${{ matrix.ld }} ./configure \
            '--prefix=${{ github.workspace }}/out' \
            --disable-werror \
            --static \
            --enable-strip \
            --enable-lto \
            --enable-safe-stack \
            --target-list=x86_64-softmmu \
            --without-default-features \
            --without-default-devices \
            --disable-curses \
            --disable-iconv \
            --enable-slirp \
            --enable-tcg \
            --enable-kvm \
            --enable-zstd
          ninja -C build install
      - uses: actions/upload-artifact@v3
        with:
          name: qemu-${{ matrix.branch }}-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.arch }}
          path: ${{ github.workspace }}/out
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: clang64, env: clang-x86_64 }
          - { sys: clang32, env: clang-i686 }
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Cache checked out qemu code
        id: cache-checkout
        uses: actions/cache@v3
        with:
          key: qemu-${{ matrix.branch }}-${{ runner.os }}-${{ matrix.env }}
          path: ${{ github.workspace }}/qemu
      - if: ${{ steps.cache-checkout.outputs.cache-hit != 'true' }}
        name: Check out qemu
        uses: actions/checkout@v3
        with:
          repository: qemu/qemu
          ref: v${{ env.QEMU_VERSION }}
          submodules: true
          path: qemu
      - name: Set up build environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: |
            diffutils
            git
            make
            ninja
            patch
            mingw-w64-${{ matrix.env }}-glib2
            mingw-w64-${{ matrix.env }}-libiconv
            mingw-w64-${{ matrix.env }}-libslirp
            mingw-w64-${{ matrix.env }}-pixman
            mingw-w64-${{ matrix.env }}-python
            mingw-w64-${{ matrix.env }}-toolchain
      - name: Build
        working-directory: ${{ github.workspace }}\qemu
        shell: msys2 {0}
        env:
          WHPX_FLAG: ${{ endsWith(matrix.sys, '64') && '--enable-whpx' || '--disable-whpx' }}
        run: |
          patch -Np1 < ../win-clang-disable-safe-stack.patch || true
          LDFLAGS=-liconv ./configure \
            '--prefix=${{ github.workspace }}/out' \
            --disable-werror \
            --static \
            --enable-strip \
            --enable-lto \
            --target-list=x86_64-softmmu \
            --without-default-features \
            --without-default-devices \
            --disable-curses \
            --disable-iconv \
            --enable-slirp \
            --enable-tcg \
            --enable-zstd \
            $WHPX_FLAG
          ninja -C build install
      - uses: actions/upload-artifact@v3
        with:
          name: qemu-${{ matrix.branch }}-${{ runner.os }}-${{ matrix.env }}
          path: ${{ github.workspace }}/out
